/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.util.ArrayList;
import model.Admin;
import model.InformasiJadwalSholat;
import model.InformasiKegiatanMasjid;
import model.PanduanTataCaraBerwudhu;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    private static final ArrayList<Admin> adminList = new ArrayList<>();
    private static final ArrayList<InformasiJadwalSholat> jadwalList = new ArrayList<>();
    private static final ArrayList<InformasiKegiatanMasjid> kegiatanList = new ArrayList<>();
    private static final ArrayList<PanduanTataCaraBerwudhu> berwudhuList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlCaraBerwudhu = new javax.swing.JPanel();
        txtJudulBerwudhu = new javax.swing.JTextField();
        txtKeteranganBerwudhu = new javax.swing.JTextField();
        txtInformasiBerwudhu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnInputBerwudhu = new javax.swing.JButton();
        pnlKegiatanMasjid = new javax.swing.JPanel();
        txtJudulKegiatan = new javax.swing.JTextField();
        txtInformasiKegiatan = new javax.swing.JTextField();
        txtKeteranganKegiatan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnInputKegiatan = new javax.swing.JButton();
        pnlJadwalSholat = new javax.swing.JPanel();
        btnInputJadwal = new javax.swing.JButton();
        txtJudulJadwal = new javax.swing.JTextField();
        txtInformasiJadwal = new javax.swing.JTextField();
        txtKeteranganJadwal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInputAdmin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnBerwudhu = new javax.swing.JButton();
        btnKegiatan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));
        pnlHome.setLayout(null);
        Content.add(pnlHome, "card6");

        pnlCaraBerwudhu.setBackground(new java.awt.Color(204, 204, 204));

        txtJudulBerwudhu.setBackground(new java.awt.Color(255, 255, 255));
        txtJudulBerwudhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulBerwudhuActionPerformed(evt);
            }
        });

        txtKeteranganBerwudhu.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganBerwudhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganBerwudhuActionPerformed(evt);
            }
        });

        txtInformasiBerwudhu.setBackground(new java.awt.Color(255, 255, 255));
        txtInformasiBerwudhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformasiBerwudhuActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("INFORMASI");

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("JUDUL");

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("KETERANGAN");

        btnInputBerwudhu.setText("INPUT");
        btnInputBerwudhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputBerwudhuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCaraBerwudhuLayout = new javax.swing.GroupLayout(pnlCaraBerwudhu);
        pnlCaraBerwudhu.setLayout(pnlCaraBerwudhuLayout);
        pnlCaraBerwudhuLayout.setHorizontalGroup(
            pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaraBerwudhuLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInputBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCaraBerwudhuLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(60, 60, 60)
                            .addComponent(txtKeteranganBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlCaraBerwudhuLayout.createSequentialGroup()
                            .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(60, 60, 60)
                            .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtInformasiBerwudhu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtJudulBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pnlCaraBerwudhuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInformasiBerwudhu, txtJudulBerwudhu, txtKeteranganBerwudhu});

        pnlCaraBerwudhuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14});

        pnlCaraBerwudhuLayout.setVerticalGroup(
            pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaraBerwudhuLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJudulBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKeteranganBerwudhu)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCaraBerwudhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtInformasiBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnInputBerwudhu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pnlCaraBerwudhuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtInformasiBerwudhu, txtJudulBerwudhu, txtKeteranganBerwudhu});

        Content.add(pnlCaraBerwudhu, "card3");

        pnlKegiatanMasjid.setBackground(new java.awt.Color(204, 204, 204));

        txtJudulKegiatan.setBackground(new java.awt.Color(255, 255, 255));

        txtInformasiKegiatan.setBackground(new java.awt.Color(255, 255, 255));
        txtInformasiKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformasiKegiatanActionPerformed(evt);
            }
        });

        txtKeteranganKegiatan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("JUDUL");

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("KETERANGAN");

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("INFORMASI");

        btnInputKegiatan.setText("INPUT");
        btnInputKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputKegiatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKegiatanMasjidLayout = new javax.swing.GroupLayout(pnlKegiatanMasjid);
        pnlKegiatanMasjid.setLayout(pnlKegiatanMasjidLayout);
        pnlKegiatanMasjidLayout.setHorizontalGroup(
            pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKegiatanMasjidLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKegiatanMasjidLayout.createSequentialGroup()
                        .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addGroup(pnlKegiatanMasjidLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(2, 2, 2)))
                            .addGroup(pnlKegiatanMasjidLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(2, 2, 2)))
                        .addGap(52, 52, 52)
                        .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtInformasiKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKeteranganKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtJudulKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInputKegiatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pnlKegiatanMasjidLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17});

        pnlKegiatanMasjidLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInformasiKegiatan, txtJudulKegiatan, txtKeteranganKegiatan});

        pnlKegiatanMasjidLayout.setVerticalGroup(
            pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKegiatanMasjidLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtJudulKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtKeteranganKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlKegiatanMasjidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtInformasiKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnInputKegiatan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pnlKegiatanMasjidLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtInformasiKegiatan, txtJudulKegiatan, txtKeteranganKegiatan});

        Content.add(pnlKegiatanMasjid, "card4");

        pnlJadwalSholat.setBackground(new java.awt.Color(204, 204, 204));

        btnInputJadwal.setText("INPUT");
        btnInputJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputJadwalActionPerformed(evt);
            }
        });

        txtJudulJadwal.setBackground(new java.awt.Color(255, 255, 255));

        txtInformasiJadwal.setBackground(new java.awt.Color(255, 255, 255));
        txtInformasiJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformasiJadwalActionPerformed(evt);
            }
        });

        txtKeteranganJadwal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("JUDUL");

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("KETERANGAN");

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("INFORMASI");

        javax.swing.GroupLayout pnlJadwalSholatLayout = new javax.swing.GroupLayout(pnlJadwalSholat);
        pnlJadwalSholat.setLayout(pnlJadwalSholatLayout);
        pnlJadwalSholatLayout.setHorizontalGroup(
            pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJadwalSholatLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInputJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlJadwalSholatLayout.createSequentialGroup()
                        .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addGroup(pnlJadwalSholatLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(2, 2, 2)))
                            .addGroup(pnlJadwalSholatLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(2, 2, 2)))
                        .addGap(52, 52, 52)
                        .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtInformasiJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKeteranganJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtJudulJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pnlJadwalSholatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel18, jLabel19, jLabel20});

        pnlJadwalSholatLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInformasiJadwal, txtJudulJadwal, txtKeteranganJadwal});

        pnlJadwalSholatLayout.setVerticalGroup(
            pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJadwalSholatLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtJudulJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtKeteranganJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlJadwalSholatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtInformasiJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnInputJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pnlJadwalSholatLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel18, jLabel19, jLabel20});

        pnlJadwalSholatLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtInformasiJadwal, txtJudulJadwal, txtKeteranganJadwal});

        Content.add(pnlJadwalSholat, "card5");

        pnlAdmin.setBackground(new java.awt.Color(204, 204, 204));

        txtId.setBackground(new java.awt.Color(255, 255, 255));

        txtName.setBackground(new java.awt.Color(255, 255, 255));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PASSWORD");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NAME");

        btnInputAdmin.setText("INPUT");
        btnInputAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAdminActionPerformed(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("USERNAME");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGap(48, 48, 48)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pnlAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        pnlAdminLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtId, txtName, txtPassword, txtUsername});

        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlAdminLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtId, txtName, txtPassword, txtUsername});

        Content.add(pnlAdmin, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI MASJID");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(102, 102, 102));

        btnAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnAdmin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnAdmin.setText("ADMIN");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnJadwal.setBackground(new java.awt.Color(204, 204, 204));
        btnJadwal.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJadwal.setForeground(new java.awt.Color(0, 0, 0));
        btnJadwal.setText("JADWAL SHOLAT");
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });

        btnBerwudhu.setBackground(new java.awt.Color(204, 204, 204));
        btnBerwudhu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBerwudhu.setForeground(new java.awt.Color(0, 0, 0));
        btnBerwudhu.setText("CARA BERWUDHU");
        btnBerwudhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerwudhuActionPerformed(evt);
            }
        });

        btnKegiatan.setBackground(new java.awt.Color(204, 204, 204));
        btnKegiatan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKegiatan.setForeground(new java.awt.Color(0, 0, 0));
        btnKegiatan.setText("KEGIATAN MASJID");
        btnKegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKegiatanActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJadwal)
                    .addComponent(btnBerwudhu)
                    .addComponent(btnKegiatan)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdmin, btnBerwudhu, btnJadwal, btnKegiatan});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJadwal)
                .addGap(18, 18, 18)
                .addComponent(btnBerwudhu)
                .addGap(18, 18, 18)
                .addComponent(btnKegiatan)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdmin, btnBerwudhu, btnJadwal, btnKegiatan});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnInputAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAdminActionPerformed
        try {
            // Validasi input kosong
            if (txtId.getText().isEmpty() || 
                txtName.getText().isEmpty() || 
                txtUsername.getText().isEmpty() || 
                txtPassword.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, 
                    "Semua field harus diisi!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validasi angka untuk ID dan password
            int id = Integer.parseInt(txtId.getText());
            String name = txtName.getText();
            String username = txtUsername.getText();
            String password = txtPassword.getText();

            // Validasi nilai tidak negatif
            if (id < 0) {
                JOptionPane.showMessageDialog(null, 
                    "ID tidak boleh negatif!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Set data ke objek Admin
            Admin objAdmin = new Admin();
            objAdmin.setId(id);
            objAdmin.setName(name);
            objAdmin.setUsername(username);
            objAdmin.setPassword(password);
            
            // Menambahkan objek harga ke dalam ArrayList
            adminList.add(objAdmin);
            
            objAdmin.infoAdmin();
            
            // Memberi konfirmasi bahwa harga berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Admin berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua harga yang ada di ArrayList
            StringBuilder allAdmin = new StringBuilder("Daftar Admin:\n");
            for (Admin admin : adminList) {
                allAdmin.append("ID: ").append(admin.getId())
                        .append(", Nama: ").append(admin.getName())
                        .append(", Username: ").append(admin.getUsername())
                        .append(", Password: ").append(admin.getPassword())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(null, allAdmin.toString(), 
                "Daftar Admin", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "ID harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputAdminActionPerformed

    private void txtInformasiBerwudhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformasiBerwudhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformasiBerwudhuActionPerformed

    private void btnInputBerwudhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputBerwudhuActionPerformed
        try {
            // Validasi input kosong
            if (txtJudulBerwudhu.getText().isEmpty() ||
                txtKeteranganBerwudhu.getText().isEmpty() ||
                txtInformasiBerwudhu.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null,
                    "Semua field harus diisi!",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            String judul = txtJudulBerwudhu.getText();
            String keterangan = txtKeteranganBerwudhu.getText();
            String information = txtInformasiBerwudhu.getText();
            
            // Validasi agar input tidak hanya angka
            if (judul.matches("\\d+")) {
                throw new Exception("Judul tidak boleh hanya angka!");
            }
            if (keterangan.matches("\\d+")) {
                throw new Exception("Keterangan tidak boleh hanya angka!");
            }
            if (information.matches("\\d+")) {
                throw new Exception("Informasi tidak boleh hanya angka!");
            }


            // Set data ke objek Admin
            PanduanTataCaraBerwudhu objBerwudhu = new PanduanTataCaraBerwudhu();
            objBerwudhu.setJudul(judul);
            objBerwudhu.setKeterangan(keterangan);
            objBerwudhu.setInformation(information);
            
            // Menambahkan objek berwudhu ke dalam ArrayList
            berwudhuList.add(objBerwudhu);
            
            objBerwudhu.infoBerwudhu();
            
            // Memberi konfirmasi bahwa berwudhu berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Berwudhu berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua berwudhu yang ada di ArrayList
            StringBuilder allBerwudhu = new StringBuilder("Daftar Berwudhu:\n");
            for (PanduanTataCaraBerwudhu berwudhu : berwudhuList) {
                allBerwudhu.append("Judul: ").append(berwudhu.getJudul())
                        .append(", Keterangan: ").append(berwudhu.getKeterangan())
                        .append(", Informasi: ").append(berwudhu.getInformation())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(null, allBerwudhu.toString(), 
                "Daftar Berwudhu", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                "Terjadi kesalahan: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputBerwudhuActionPerformed

    private void txtInformasiKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformasiKegiatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformasiKegiatanActionPerformed

    private void btnInputJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputJadwalActionPerformed
        try {
            // Validasi input kosong
            if (txtJudulJadwal.getText().isEmpty() ||
                txtKeteranganJadwal.getText().isEmpty() ||
                txtInformasiJadwal.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null,
                    "Semua field harus diisi!",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            String judul = txtJudulJadwal.getText();
            String keterangan = txtKeteranganJadwal.getText();
            String information = txtInformasiJadwal.getText();
            
            // Validasi agar input tidak hanya angka
            if (judul.matches("\\d+")) {
                throw new Exception("Judul tidak boleh hanya angka!");
            }
            if (keterangan.matches("\\d+")) {
                throw new Exception("Keterangan tidak boleh hanya angka!");
            }
            if (information.matches("\\d+")) {
                throw new Exception("Informasi tidak boleh hanya angka!");
            }

            // Set data ke objek Admin
            InformasiJadwalSholat objJadwal = new InformasiJadwalSholat();
            objJadwal.setJudul(judul);
            objJadwal.setKeterangan(keterangan);
            objJadwal.setInformation(information);

            objJadwal.infoJadwal();
            
            // Menambahkan objek jadwal ke dalam ArrayList
            jadwalList.add(objJadwal);
            
            // Memberi konfirmasi bahwa jadwal berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Jadwal berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua jadwal yang ada di ArrayList
            StringBuilder allJadwal = new StringBuilder("Daftar Jadwal:\n");
            for (InformasiJadwalSholat jadwal : jadwalList) {
                allJadwal.append("Judul: ").append(jadwal.getJudul())
                        .append(", Keterangan: ").append(jadwal.getKeterangan())
                        .append(", Informasi: ").append(jadwal.getInformation())
                        .append("\n");
            }
            
            JOptionPane.showMessageDialog(null, allJadwal.toString(), 
                "Daftar Jadwal", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                "Terjadi kesalahan: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputJadwalActionPerformed

    private void btnInputKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputKegiatanActionPerformed
        try {
            // Validasi input kosong
            if (txtJudulKegiatan.getText().isEmpty() ||
                txtKeteranganKegiatan.getText().isEmpty() ||
                txtInformasiKegiatan.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null,
                    "Semua field harus diisi!",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            String judul = txtJudulKegiatan.getText();
            String keterangan = txtKeteranganKegiatan.getText();
            String information = txtInformasiKegiatan.getText();
            
            // Validasi agar input tidak hanya angka
            if (judul.matches("\\d+")) {
                throw new Exception("Judul tidak boleh hanya angka!");
            }
            if (keterangan.matches("\\d+")) {
                throw new Exception("Keterangan tidak boleh hanya angka!");
            }
            if (information.matches("\\d+")) {
                throw new Exception("Informasi tidak boleh hanya angka!");
            }


            // Set data ke objek Admin
            InformasiKegiatanMasjid objKegiatan = new InformasiKegiatanMasjid();
            objKegiatan.setJudul(judul);
            objKegiatan.setKeterangan(keterangan);
            objKegiatan.setInformation(information);
                        
            // Menambahkan objek kegiatan ke dalam ArrayList
            kegiatanList.add(objKegiatan);
            
            objKegiatan.infoKegiatan();
            
            // Memberi konfirmasi bahwa kegiatan berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Kegiatan berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua kegiatan yang ada di ArrayList
            StringBuilder allKegiatan = new StringBuilder("Daftar kegiatan:\n");
            for (InformasiKegiatanMasjid kegiatan : kegiatanList) {
                allKegiatan.append("Judul: ").append(kegiatan.getJudul())
                        .append(", Keterangan: ").append(kegiatan.getKeterangan())
                        .append(", Informasi: ").append(kegiatan.getInformation())
                        .append("\n");
            }
            
            JOptionPane.showMessageDialog(null, allKegiatan.toString(), 
                "Daftar Kegiatan", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                "Terjadi kesalahan: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputKegiatanActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        Content.removeAll(); 
        Content.add(pnlAdmin);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        Content.removeAll(); 
        Content.add(pnlJadwalSholat);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnBerwudhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerwudhuActionPerformed
        Content.removeAll(); 
        Content.add(pnlCaraBerwudhu);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnBerwudhuActionPerformed

    private void btnKegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKegiatanActionPerformed
        Content.removeAll(); 
        Content.add(pnlKegiatanMasjid);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKegiatanActionPerformed

    private void txtKeteranganBerwudhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganBerwudhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganBerwudhuActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtInformasiJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformasiJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformasiJadwalActionPerformed

    private void txtJudulBerwudhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulBerwudhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulBerwudhuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBerwudhu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputAdmin;
    private javax.swing.JButton btnInputBerwudhu;
    private javax.swing.JButton btnInputJadwal;
    private javax.swing.JButton btnInputKegiatan;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKegiatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlCaraBerwudhu;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlJadwalSholat;
    private javax.swing.JPanel pnlKegiatanMasjid;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtInformasiBerwudhu;
    private javax.swing.JTextField txtInformasiJadwal;
    private javax.swing.JTextField txtInformasiKegiatan;
    private javax.swing.JTextField txtJudulBerwudhu;
    private javax.swing.JTextField txtJudulJadwal;
    private javax.swing.JTextField txtJudulKegiatan;
    private javax.swing.JTextField txtKeteranganBerwudhu;
    private javax.swing.JTextField txtKeteranganJadwal;
    private javax.swing.JTextField txtKeteranganKegiatan;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
